language: php

php:
  - '7.3'

before_script:
  - travis_retry composer self-update -d web
  - travis_retry composer install --prefer-source --no-interaction --dev -d web --optimize-autoloader
  - cd web && php artisan config:cache

script:
  - composer psr-check
  - composer coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 'a55e3e8e-e439-4626-af0b-f5371161d77e'

branches:
  except:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false
