language: php

php:
  - '7.3'

before_script:
  - travis_retry composer self-update -d web
  - travis_retry install --prefer-source --no-interaction --dev -d web

script:
  - composer psr-check -d web
  - composer coverage -d web

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false
