codecov:
  token: "a55e3e8e-e439-4626-af0b-f5371161d77e"
  require_ci_to_pass: yes
  ci:
    - "travis.org"
  max_report_age: off
  disable_default_path_fixes: no
  wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 80%
        threshold: 70%
        base: auto
        branches:
          - master
        if_ci_failed: error
        only_pulls: false
        paths:
          - web/src
          - web/app/Http/Controllers

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
