version: '3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  php-fpm:
    image: api-php-fpm:latest
    build:
      context: ./php-fpm
    container_name: api-php
    working_dir: /web
    volumes:
    - ../web:/web
    tty: true
    networks:
      - frontend

  nginx:
    image: api-nginx:latest
    build:
      context: ./nginx
    container_name: api-nginx
    working_dir: /web
    volumes:
      - ../web:/web
    depends_on:
      - php-fpm
    ports:
    - 80:80
    - 443:443
    networks:
      - frontend
      - backend

  mysql:
    image: api-mysql:latest
    build:
      context: ./mysql
    container_name: api-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: api-mysql-admin:lastest
    build:
      context: ./phpmyadmin
    container_name: api-mysql-admin
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=api-mysql
      - PMA_ABSOLUTE_URI=http://admin.tinnyapi.local/
    networks:
      - frontend
      - backend
