version: '3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  php-fpm:
    image: php-fpm:latest
    build:
      context: ./php-fpm
    container_name: web-php-fpm
    working_dir: /web
    volumes:
    - ../web:/web
    tty: true
    networks:
      - frontend

  nginx:
    image: web-nginx-php:latest
    build:
      context: ./nginx
    container_name: web-nginx-php
    working_dir: /web
    depends_on:
      - php-fpm
    ports:
    - 80:80
    - 443:443
    networks:
      - frontend
      - backend

  mysql:
    image: web-mysql:latest
    build:
      context: ./mysql
    container_name: web-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    - ./mysql/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend

  phpmyadmin:
    image: web-mysql-admin:lastest
    build:
      context: ./phpmyadmin
    container_name: web-mysql-admin
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=web-mysql
      - PMA_ABSOLUTE_URI=http://admin.tinnyapi.local/
    networks:
      - frontend
      - backend
